services:
    creonit_admin.content_plugin:
        class: Creonit\ContentBundle\Admin\ContentPlugin
        tags: [ {name: creonit_admin.plugin} ]

    Creonit\ContentBundle\Content\ContentService:
        autowire: true
        autoconfigure: true
        public: true

    creonit_content:
        alias: Creonit\ContentBundle\Content\ContentService
        public: true
